# Generated by Django 4.1.3 on 2022-12-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_profile_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='profile',
        ),
    ]
